### ISSUE TITLE
Matlab syntax highlighting

### ISSUE THREAD

**Issue by bobturneruk** [RSE-Sheffield/RSE-Sheffield.github.io#157]
![image](https://user-images.githubusercontent.com/34244196/66299293-23608f00-e8eb-11e9-88b4-7a4b65e3e9b5.png)

If the language of a code block is set to matlab, the code is displayed dark on light, without syntax highlighting, presumably as the language is not recognised. It should be light on dark, as per Python, even if syntax highlighting is not possible.

**Comment by ptheywood** [comment]
Jekyll should be using `rouge` for syntax highlighting (essentially a ruby version of pygments), which shold have language support for matlab ([It has a lexer listed on their docs](https://rouge-ruby.github.io/docs/Rouge/Lexers/Matlab.html))

In which case it could be that the theme we have doesn't support it? (although it should just be generic styling for all languages). 

Having said that, GH pages is still running jekyll 3.8.5 (https://pages.github.com/versions/) rather than the latest 4.0 which dropped support for pygments in place of rogue, so perhaps we aren't using rouge.

**Comment by ptheywood** [comment]
Looks like `Prism` is used for client side syntax highlighting, without generic language support by the theme we use. 
Might be better to replace prism with a generic pygments style syntax highlighter?
