### ISSUE TITLE
Site is not accessible from https://rse.sheffield.ac.uk/

### ISSUE THREAD

**Issue by willfurnass** [RSE-Sheffield/RSE-Sheffield.github.io#212]
Raised by @twinkarma:

> You're directed to a github 404 page so maybe there's some kind of domain alias setting on github pages to allow the website to work?
> 
> Since shef.ac.uk and sheffield.ac.uk are used interchangeably it seems sensible to sort this out.

**Comment by ptheywood** [comment]
GH Pages can only have a single custom domain. Probably have to set up a DNS redirect from rse.sheffield.ac.uk to rse.shef.ac.uk (via cpanel?).

Or would we want it the other way around, as i seem to think the university branding prefers sheffield.ac.uk to shef.ac.uk as the canonical url.

**Comment by willfurnass** [comment]
(For refererence `rse.sheffield.ac.uk.` and `rse.shef.ac.uk.` have a `CNAME` record of `rse-sheffield.github.io.`, with `rse-sheffield.github.io.` having multiple `A` records that point at IPs of GitHub's servers)  

We have a `CNAME` file in our repo that contains just `rse.shef.ac.uk` and in the repo settings *Custom domain* is also set to that (value automatically picked up from the `CNAME` file?). I'm guessing that GH Pages content is only served up by GH's web servers for explicitly-specified custom domains.  As @ptheywood mentions, the `CNAME` file (and the *Custom domain* setting) can only reference one domain. 

[GH's docs](https://help.github.com/en/github/working-with-github-pages/troubleshooting-custom-domains-and-github-pages#cname-errors) suggest making one of our custom domains a DNS alias of the other i.e. make  `rse.sheffield.ac.uk` an alias for `rse.shef.ac.uk` instead of `rse-sheffield.github.io`.  However, I don't think that'll work for us as we've told GH to enforce HTTPS for our site so behind the scenes it'll be using LetsEncrypt to generate TLS certs for just the custom domain it knows about so attempts to access https://rse.sheffield.ac.uk will still fail.

An HTTP redirect might work better.  IT Services have a web appliance that could be used for this - I'll ask them about it.

**Comment by willfurnass** [comment]
@ptheywood Shout if you think I've missed something here!

**Comment by ptheywood** [comment]
Looks good to me. The cname option is from the file (and if you update the option it changes the file).

**Comment by ptheywood** [comment]
@willfurnass Did you get any response about this from IT Services?

**Comment by willfurnass** [comment]
Recommend setting up a redirect site similar to

https://github.com/rcgsheffield/sheffield_hpc_redirect

Think that is the simplest option.

**Comment by Robadob** [comment]
> Recommend setting up a redirect site similar to
> 
> [rcgsheffield/sheffield_hpc_redirect](https://github.com/rcgsheffield/sheffield_hpc_redirect)
> 
> Think that is the simplest option.

Have now set this up [here](https://github.com/RSE-Sheffield/sheffield_rse_redirect), but can't set custom domain as `rse.sheffield.ac.uk` inside the settings, it errors as all ready verified (by the org?) so may need to be done by an org admin.

As noted by James Moore on slack, may still need to nag ITS to re-enable the DNS record after this has been completed.

**Comment by ptheywood** [comment]
I'd previoulsy opened https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/pull/735 and created https://github.com/RSE-Sheffield/rse.sheffield.ac.uk which is a full mirror of the main site, deployed by PAT when this repo is updated, but the cname record didn't set correctly due to someone attempting to hijack the domain (https://github.com/Wesleyhar2007/rse.sheffield.ac.uk)

We (an org admin) need to follow:

https://docs.github.com/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages

this requires a DNS text record setting with specific values, so the domain can be verified by the RSE-Sheffield org, then it should be possible to enable the custom domain on the mirror site. 

I think this is probably prefereable to the [simple redirect](https://github.com/RSE-Sheffield/sheffield_rse_redirect), as all pages will be accessible from either domain (at the cost of having to renew a PAT, and/or set up a cron CI job)?. One of these options can then be removed.

**Comment by Robadob** [comment]
> Have now set this up [here](https://github.com/RSE-Sheffield/sheffield_rse_redirect), but can't set custom domain as `rse.sheffield.ac.uk` inside the settings, it errors as all ready verified (by the org?) so may need to be done by an org admin.


This repo can be killed off once Pete's solution is working.

**Comment by ptheywood** [comment]
The rse.sheffield.ac.uk domain is now verified on the RSE-Sheffield organisation.

However, when attempting to set this as the cname in the repo settings it fails, with the error that it is already taken, and to verify the domain (which is why we verified the domain in the first place).

**Comment by ptheywood** [comment]
Enabling the cname setting worked for Twin but not for me (Not sure why, both org admins, maybe because Twin verified it or because I tried to set it pre verification?).

DNS CNAME required, which has been requested so once set the site should become accessible, and we'll just need to merge #735 and/or tweak https://github.com/RSE-Sheffield/rse.sheffield.ac.uk.

**Comment by ptheywood** [comment]
The site is now accessible through rse.sheffield.ac.uk, as a mirror of rse.shef.ac.uk, and will be re generated any time rse.shef.ac.uk is updated.
